#ifndef ATMOSPHERIC_DEPTH_CUE_APPEND_SHARED_FXH
#define ATMOSPHERIC_DEPTH_CUE_APPEND_SHARED_FXH

#ifndef ATMOSPHERIC_DEPTH_CUE_APPEND_LIBRARY_MODE
#define ATMOSPHERIC_DEPTH_CUE_APPEND_LIBRARY_MODE
#endif
#include "../AtmosphericDepthCue_append.fx"

#endif