#ifndef DEPTH_BAND_ASSIST_APPEND_SHARED_FXH
#define DEPTH_BAND_ASSIST_APPEND_SHARED_FXH

#ifndef DEPTH_BAND_ASSIST_APPEND_LIBRARY_MODE
#define DEPTH_BAND_ASSIST_APPEND_LIBRARY_MODE
#endif
#include "../DepthBandAssist_append.fx"

#endif