#ifndef DEPTH_COORDINATE_PROBE_APPEND_SHARED_FXH
#define DEPTH_COORDINATE_PROBE_APPEND_SHARED_FXH

#ifndef DEPTH_COORDINATE_PROBE_APPEND_LIBRARY_MODE
#define DEPTH_COORDINATE_PROBE_APPEND_LIBRARY_MODE
#endif
#include "../DepthCoordinateProbe_append.fx"

#endif
