#ifndef DEPTH_OUTLINE_OVERLAY_APPEND_SHARED_FXH
#define DEPTH_OUTLINE_OVERLAY_APPEND_SHARED_FXH

#ifndef DEPTH_OUTLINE_OVERLAY_APPEND_LIBRARY_MODE
#define DEPTH_OUTLINE_OVERLAY_APPEND_LIBRARY_MODE
#endif
#include "../DepthOutlineOverlay_append.fx"

#endif
