#ifndef DEPTH_LAYERED_PAINTERLY_APPEND_SHARED_FXH
#define DEPTH_LAYERED_PAINTERLY_APPEND_SHARED_FXH

#ifndef DEPTH_LAYERED_PAINTERLY_APPEND_LIBRARY_MODE
#define DEPTH_LAYERED_PAINTERLY_APPEND_LIBRARY_MODE
#endif
#include "../DepthLayeredPainterly_append.fx"

#endif
