#ifndef DEPTH_FOG_STYLIZATION_APPEND_SHARED_FXH
#define DEPTH_FOG_STYLIZATION_APPEND_SHARED_FXH

#ifndef DEPTH_FOG_STYLIZATION_APPEND_LIBRARY_MODE
#define DEPTH_FOG_STYLIZATION_APPEND_LIBRARY_MODE
#endif
#include "../DepthFogStylization_append.fx"

#endif
