#ifndef HYPEROPIA_DEPTH_BLUR_APPEND_SHARED_FXH
#define HYPEROPIA_DEPTH_BLUR_APPEND_SHARED_FXH

#ifndef HYPEROPIA_DEPTH_BLUR_APPEND_LIBRARY_MODE
#define HYPEROPIA_DEPTH_BLUR_APPEND_LIBRARY_MODE
#endif
#include "../HyperopiaDepthBlur_append.fx"

#endif
