#ifndef MYOPIA_DEPTH_BLUR_APPEND_SHARED_FXH
#define MYOPIA_DEPTH_BLUR_APPEND_SHARED_FXH

#ifndef MYOPIA_DEPTH_BLUR_APPEND_LIBRARY_MODE
#define MYOPIA_DEPTH_BLUR_APPEND_LIBRARY_MODE
#endif
#include "../MyopiaDepthBlur_append.fx"

#endif
