#ifndef NEAR_BRIGHT_FAR_DARK_APPEND_SHARED_FXH
#define NEAR_BRIGHT_FAR_DARK_APPEND_SHARED_FXH

#ifndef NEAR_BRIGHT_FAR_DARK_APPEND_LIBRARY_MODE
#define NEAR_BRIGHT_FAR_DARK_APPEND_LIBRARY_MODE
#endif
#include "../NearBrightFarDark_append.fx"

#endif