#ifndef SILVER_DEPTH_EDGE_APPEND_SHARED_FXH
#define SILVER_DEPTH_EDGE_APPEND_SHARED_FXH

#ifndef SILVER_DEPTH_EDGE_APPEND_LIBRARY_MODE
#define SILVER_DEPTH_EDGE_APPEND_LIBRARY_MODE
#endif
#include "../SilverDepthEdge_append.fx"

#endif